# Generated by Django 5.2.8 on 2025-11-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_size_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.price_range'),
        ),
    ]
