# Generated by Django 5.2.8 on 2025-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_product_price_delete_price_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
            ],
        ),
    ]
