# Generated by Django 5.2.8 on 2025-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_discount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
