# Generated by Django 5.2.8 on 2025-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_register_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
