# Generated by Django 5.2.8 on 2026-01-06 08:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_order_coupon_discount_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
